server:
  port: 8888

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #eureka界面上显示的地址
    preferIp-address: true  # eureka界面上显示的是否是IP
    hostname: ${spring.cloud.client.ip-address}:${server.port} #eureka状态栏显示的地址
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/quietlly/config.git
          basedir: ../config-repo
          username: quietlly
          password: Zx123456!!
          search-paths: config
      label: ${spring.profiles.active}
  kafka:
    bootstrap-servers:
      - 192.168.0.204:2181